### ISSUE TITLE
Can't connect to playit.gg

### ISSUE THREAD

**Issue by turtley12** [maxomatic458/playit-minecraft-mod#10]
Hi,

I'm trying to setup this mod and it's not quite connecting to playit.

I can create the agent and tunnel, but then it just gives me 

```
01.07 21:02:09 [Server] Thread-35/ERROR got error during setup: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Multiple fields representing property "valheim": gg.playit.api.models.TunnelType#Valheim vs gg.playit.api.models.TunnelType#Terraria
01.07 21:02:09 [Server] INFO at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
```

and it doesn't store the secret in it's config.

In hopes that the error was just in the getting the secret part, I ran a 1.19 version of this mod with 1.19 fabric, got it to get a secret like it was supposed to, and then tried that secret with 1.21 versions of fabric and this mod, and the same thing as before happened.

Any suggestions for what more I could do to troubleshoot?

**Comment by maxomatic458** [comment]
@Turtley12 have you tried deleting the agent on the playit.gg website and then try to bind it again?

And also make sure to not manually create any tunnels on the agent (the mod is only able to tunnel the raw minecraft connection, so dynmap or geyser or anyting else that would require a seperate tunnel will not work)

**Comment by maxomatic458** [comment]
and you are experiencing that problem on fabric 1.21?

**Comment by turtley12** [comment]
> @Turtley12 have you tried deleting the agent on the playit.gg website and then try to bind it again?

Yep I tried that
> And also make sure to not manually create any tunnels on the agent (the mod is only able to tunnel the raw minecraft connection, so dynmap or geyser or anyting else that would require a seperate tunnel will not work)

Ah ok. That was what I wanted to eventually use this for, but for now I was testing it with just the main server port.

I was doing my earlier tests on a server host as it was the most convenient, I'll test it again locally in the morning.

> and you are experiencing that problem on fabric 1.21?

Yep

Turtley

**Comment by maxomatic458** [comment]
If you want to use it for different apps you should probably use the playit program instead

Ill check if im able to replicate the issue
its most likely something with 1.21 (i havent tested that version explicitly)

**Comment by maxomatic458** [comment]
Ill close that because i think that error is just the result of manually tempering with the plugin agent on the website.
your not supposed to touch the agent once its setup with the mod.

If you think its not because of that feel free to @ me here

**Comment by maxomatic458** [comment]
@Turtley12 this was fixed in the latest version, just letting you know (still wasnt able to replicate it)
