### ISSUE TITLE
[UPDATE] Update to 1.21

### ISSUE THREAD

**Issue by itisphxjupiter** [maxomatic458/playit-minecraft-mod#11]
maxomatic458,

I rely on this mod to let the members of my server join without needing to figure out how the Playit application works with Docker containers, and I think it is beneficial to have a Fabric mod for Playit!

Thanks,
itsphxjupiter and the members of CCC season 2

**Comment by maxomatic458** [comment]
The current versions might still work with 1.21 (they have no set version cap)

But its untested and stuff might not work

**Comment by itisphxjupiter** [comment]
It appears to be working in 1.21! Thanks for the suggestion. I haven't tested it to the extent that would be needed before saying it works on 1.21 (i've only had it up on my server for around 10 hours), but I will keep records of if it goes down and report the bugs, if you would like!

Thanks!

**Comment by maxomatic458** [comment]
Yea the plugin doesnt rely on a lot of forge specific features (so it might still work for a few feature versions)
But its certainly not a good practise to do it like that, ill try to make releases on a per version bases in the future probably

Ill close this once i can confirm the current version fully works on 1.21
