### ISSUE TITLE
UKNOW HOST

### ISSUE THREAD

**Issue by SuparHacka** [maxomatic458/playit-minecraft-mod#4]
i set up everything but when i try to connect from another wifi, minecraft throws me uknow host

**Comment by maxomatic458** [comment]
@SuparHacka its possible that the ISP is blocking the joinmc.link / ply.gg domain; you can try to use the numerical IPv4 of the tunnel instead, you can see it on the playit website (click on the tunnel, and you can see it at the top of the page below the .joinmc.link domain)

**Comment by SuparHacka** [comment]
yeah but what do i have to do with that number, i put it in the direct connectrion to the server and cant join. i also tried joinmc.link:thenumber and didnt worked.

**Comment by maxomatic458** [comment]
@SuparHacka can you ping that IPv4 (without port)
In your cmd?

The IP might get blocked by your ISP

Also check that no antivirus programs are causing problems

**Comment by SuparHacka** [comment]
ping it and i get response but just after deleting the plugin and initializing playit directly into my server. honestly i have no idea why the pluging didnt work (it worked in 1.19 paper but in 1.20 forge did not.

**Comment by maxomatic458** [comment]
ill close this issue because gettigns Unknown host is a client problem (so your ISP might block the domain)
