### ISSUE TITLE
[BUG] mod not being registered (forge 1.19)

### ISSUE THREAD

**Issue by HundreadK** [maxomatic458/playit-minecraft-mod#7]
I'm trying to test the commands in my forge server but keep getting errors and i cant seem to find the information needed to make a tunnel. any assistance would be appreciated 

to give more details im running a forge server thru crafty controller 
![image](https://github.com/maxomatic458/playit-minecraft-mod/assets/117326842/14caf73b-8c2d-4b76-a87f-664e3332fdd8)

**Comment by maxomatic458** [comment]
@HundreadK if you start your server, it should log that your tunnel is online in the server console.
To use the playit command you need to have OP.
What mc version are you on?
You should find all the info you need in your servers console (or in the chat if you have op)

**Comment by HundreadK** [comment]
Im on version 1.19.2 
I do have OP

**Comment by maxomatic458** [comment]
@HundreadK can you confirm that the mod is loaded by running ``/datapack list`` and it should show up there.

also check your server logs for anything useful.

**Comment by HundreadK** [comment]
Hello sorry for the late reply was at work but after running the requested command it seems that its not loaded or running 
i think i may have put the file in the wrong location 
i placed playit-forge-1.3.1-1.19.X-1.20.X in the mods folder  is this correct or does it need to be placed in another location?

**Comment by maxomatic458** [comment]
@HundreadK no the mods folder is fine

Do you have other mods installed as well? Do they load correctly?

**Comment by HundreadK** [comment]
Yes in running All the mods 8 and they seem to load and are working well

**Comment by maxomatic458** [comment]
Okay i see
Ill have a look at it tomorrow

Also did you download it from modrinth/curseforge or github?

**Comment by HundreadK** [comment]
Modrinth

**Comment by maxomatic458** [comment]
@HundreadK i installed the atm8 server pack from curseforge and added the playit mod (this one https://modrinth.com/mod/playit-gg/version/1.3.1)
and i could not replicate the issue

the mod correctly registered for me

**Comment by maxomatic458** [comment]
can you try adding another mod to the modpack?
maybe you are doing something wrong adding a mod

maybe its crafty controller not loading any other mods

**Comment by HundreadK** [comment]
Sure ill try to add another mod later today and try making another server 
But just to cross my Ts and dot my Is 
I should add the playit mod to the section where Atm8 mods go correct

**Comment by HundreadK** [comment]
did you just upload the jar file  of did  you unzip it to the mod folder?

**Comment by HundreadK** [comment]
used direct link that you attached for mod and got it to work 
thanks for the assistance
